name: ocr
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.7+13

environment:
  sdk: ">=2.7.0 <3.0.0"
 


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_easyloading: ^3.0.0
  # flutter_restart: 0.0.3
  # flutter_stetho:
  #   git:
  #     url: git://github.com/jasonlewicki/flutter_stetho.git
  #     ref: master
  flutter_typeahead: ^4.1.1
  http: ^0.13.4 
  intl: ^0.18.0 
  multi_select_flutter: ^4.0.0
  permission_handler: ^10.2.0
  shared_preferences: ^2.0.17
  # tesseract_ocr: ^0.3.1
  # flutter_mobile_vision: ^0.1.4+1
  # custom_camera: ^0.0.6
  # flutter_camera_ml_vision: ^3.0.1
  # google_ml_kit: ^0.7.0
  image_picker: ^0.8.3+3
  image_cropper: ^3.0.1
  crop: ^0.5.1+1
  # camera: ^0.8.1
  # photo_view: ^0.12.0
  simple_corner_detection:
    path: /Users/codesncoffee/Desktop/simple_corner_detection    
  #Define simple_corner_detection folder path
  path_provider: ^2.0.2
  provider: ^6.0.5
  ext_storage: ^1.0.3
  pdf: ^3.7.4
  # flutter_speed_dial: ^4.3.0
  pull_to_refresh: ^2.0.0
  flutter_pdfview: ^1.2.1
    # ^1.2.1
  auto_size_text: ^3.0.0
  # native_pdf_renderer: 
  native_pdf_renderer: ^5.0.0+1
  # camera: ^0.9.4+19
  camera: ^0.10.2+1
  fvm: ^2.4.1
  thumbnailer: ^2.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_launcher_icons: "^0.8.0"
  # flutter_launcher_name: "^0.0.1"
  # change_app_package_name: ^0.1.3

# flutter_launcher_name:
#   name: "Uploads"
# flutter_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/images/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # - assets/
    - assets/images/
    # - assets/tessdata/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages